INSERT INTO usuarios (usu_nome, usu_email, usu_senha, usu_data_cadastro) 
VALUES 
('João Silva', 'joao.silva@email.com', '12345678', NOW()),
('Maria Souza', 'maria.souza@email.com', '87654321', NOW()),
('Carlos Oliveira', 'carlos.oliveira@email.com', 'abcd1234', NOW()),
('Ana Lima', 'ana.lima@email.com', 'senha123', NOW()),
('Fernando Costa', 'fernando.costa@email.com', 'qwerty12', NOW()),
('Patrícia Mendes', 'patricia.mendes@email.com', 'pass1234', NOW()),
('Roberto Nunes', 'roberto.nunes@email.com', 'segura12', NOW()),
('Camila Rocha', 'camila.rocha@email.com', 'teste123', NOW()),
('André Martins', 'andre.martins@email.com', 'abcd5678', NOW()),
('Juliana Alves', 'juliana.alves@email.com', 'juliana1', NOW()),
('Lucas Ferreira', 'lucas.ferreira@email.com', 'lucas123', NOW()),
('Eduarda Lima', 'eduarda.lima@email.com', 'eduarda7', NOW()),
('Bruno Cardoso', 'bruno.cardoso@email.com', 'bruno56', NOW()),
('Gabriela Souza', 'gabriela.souza@email.com', 'gabisouz', NOW()),
('Ricardo Mendes', 'ricardo.mendes@email.com', 'ricardo9', NOW()),
('Vanessa Carvalho', 'vanessa.carvalho@email.com', 'vanessa1', NOW()),
('Fábio Moreira', 'fabio.moreira@email.com', 'fabio321', NOW()),
('Tatiane Oliveira', 'tatiane.oliveira@email.com', 'tatiane9', NOW()),
('Gustavo Ribeiro', 'gustavo.ribeiro@email.com', 'gustavo7', NOW()),
('Letícia Gomes', 'leticia.gomes@email.com', 'leticia5', NOW()),
('Renato Silva', 'renato.silva@email.com', 'renato66', NOW()),
('Mariana Santos', 'mariana.santos@email.com', 'mari88', NOW()),
('Thiago Almeida', 'thiago.almeida@email.com', 'thiago44', NOW()),
('Jéssica Fernandes', 'jessica.fernandes@email.com', 'jessica2', NOW()),
('Rodrigo Nogueira', 'rodrigo.nogueira@email.com', 'rodrigo9', NOW()),
('Amanda Castro', 'amanda.castro@email.com', 'amanda77', NOW()),
('Felipe Araújo', 'felipe.araujo@email.com', 'felipe33', NOW()),
('Simone Costa', 'simone.costa@email.com', 'simone22', NOW()),
('Bruna Sales', 'bruna.sales@email.com', 'bruna10', NOW()),
('Paulo Henrique', 'paulo.henrique@email.com', 'paulo55', NOW());
SELECT * FROM usuarios;


INSERT INTO categorias ( categ_nome, categ_icone) VALUES
( 'Documentos Pessoais', 'icon-documents.png'),
('Carteira de Identidade', 'icon-idcard.png'),
( 'CNH (Carteira de Habilitação)', 'icon-cnh.png'),
( 'Passaporte', 'icon-passport.png'),
( 'Cartões Bancários', 'icon-creditcard.png'),
( 'Dinheiro', 'icon-money.png'),
( 'Celulares', 'icon-phone.png'),
( 'Notebooks', 'icon-laptop.png'),
( 'Tablets', 'icon-tablet.png'),
( 'Fones de Ouvido', 'icon-headphones.png'),
( 'Chaves de Casa', 'icon-keys.png'),
( 'Chaves de Carro', 'icon-car-keys.png'),
( 'Bolsas e Mochilas', 'icon-bag.png'),
( 'Malas de Viagem', 'icon-suitcase.png'),
( 'Roupas', 'icon-clothes.png'),
( 'Óculos de Grau', 'icon-glasses.png'),
( 'Óculos de Sol', 'icon-sunglasses.png'),
( 'Relógios', 'icon-watch.png'),
( 'Pulseiras e Anéis', 'icon-jewelry.png'),
('Brinquedos', 'icon-toys.png'),
('Livros e Cadernos', 'icon-books.png'),
( 'Instrumentos Musicais', 'icon-music.png'),
('Equipamentos Esportivos', 'icon-sports.png'),
( 'Fitas e Pen Drives', 'icon-pendrive.png'),
('Ferramentas', 'icon-tools.png'),
( 'Câmeras Fotográficas', 'icon-camera.png'),
( 'Patinetes e Bicicletas', 'icon-bike.png'),
('Animais Perdidos', 'icon-pets.png'),
( 'Remédios e Medicamentos', 'icon-medicine.png'),
( 'Outros', 'icon-other.png');
SELECT * FROM categorias;


INSERT INTO Objetos (categ_id, usu_id, obj_descricao, obj_foto, obj_local_encontrado, obj_data_publicacao, obj_status, obj_encontrado)
VALUES 
(1, 1, 'Celular Samsung preto com capinha azul', 'celular1.png', 'Biblioteca', NOW(), 'achado', 0),
(2, 3, 'Jaqueta azul tamanho M com bolso rasgado', 'jaqueta1.png', 'Quadra de esportes', NOW(), 'perdido', 0),
(3, 5, 'Relógio de pulso prata marca Casio', 'relogio1.png', 'Cantina', NOW(), 'achado', 1),
(4, 2, 'Caderno de Matemática capa vermelha', 'caderno1.png', 'Sala 203', NOW(), 'achado', 0),
(5, 4, 'Chaveiro com 3 chaves e chaveiro do Batman', 'chaveiro1.png', 'Estacionamento', NOW(), 'perdido', 0),
(1, 6, 'Fone de ouvido preto JBL', 'fone1.png', 'Sala de estudos', NOW(), 'achado', 1),
(3, 7, 'Carteira de couro marrom sem documentos', 'carteira1.png', 'Corredor principal', NOW(), 'perdido', 0),
(2, 8, 'Blusa de moletom cinza tamanho G', 'moletom1.png', 'Auditório', NOW(), 'achado', 0),
(4, 9, 'Estojo azul com várias canetas coloridas', 'estojo1.png', 'Biblioteca', NOW(), 'achado', 0),
(5, 10, 'Chave de carro com chaveiro vermelho', 'chave2.png', 'Portaria', NOW(), 'reservado', 0),
(1, 11, 'Óculos de sol Ray-Ban preto', 'oculos1.png', 'Cantina', NOW(), 'achado', 1),
(2, 12, 'Garrafa térmica azul com adesivos', 'garrafa1.png', 'Sala dos professores', NOW(), 'reservado', 0),
(3, 13, 'Fone Bluetooth branco Apple', 'fone2.png', 'Banheiro do 2º andar', NOW(), 'achado', 0),
(4, 14, 'Bolsinha vermelha com maquiagem', 'bolsa1.png', 'Laboratório de química', NOW(), 'achado', 1),
(5, 15, 'Cinto de couro marrom com fivela prata', 'cinto1.png', 'Vestiário masculino', NOW(), 'perdido', 0),
(1, 16, 'Mouse sem fio Logitech preto', 'mouse1.png', 'Sala de informática', NOW(), 'achado', 0),
(2, 17, 'Boné Adidas azul escuro', 'bone1.png', 'Pátio', NOW(), 'achado', 0),
(3, 18, 'Carregador de celular Motorola branco', 'carregador1.png', 'Biblioteca', NOW(), 'reservado', 0),
(4, 19, 'Pulseira dourada fina', 'pulseira1.png', 'Corredor do bloco B', NOW(), 'achado', 1),
(5, 20, 'Livro "O Pequeno Príncipe" capa amarela', 'livro1.png', 'Auditório', NOW(), 'perdido', 0),
(1, 21, 'Relógio digital preto XIAOMI', 'relogio2.png', 'Quadra esportiva', NOW(), 'achado', 0),
(2, 22, 'Chave única com pingente azul', 'chave3.png', 'Banheiro feminino', NOW(), 'achado', 1),
(3, 23, 'Jaqueta jeans tamanho P', 'jaqueta2.png', 'Biblioteca', NOW(), 'perdido', 0),
(4, 24, 'Pasta com documentos universitários', 'pasta1.png', 'Sala dos professores', NOW(), 'achado', 1),
(5, 25, 'Bicicleta vermelha com adesivos', 'bike1.png', 'Estacionamento', NOW(), 'reservado', 0),
(1, 26, 'Headset gamer HyperX preto', 'headset1.png', 'Sala de informática', NOW(), 'achado', 0),
(2, 27, 'Mochila preta com chaveiro de pelúcia', 'mochila1.png', 'Cantina', NOW(), 'achado', 1),
(3, 28, 'Tablet Samsung branco', 'tablet1.png', 'Biblioteca', NOW(), 'reservado', 0),
(4, 29, 'Garrafa de vidro verde com tampa branca', 'garrafa2.png', 'Sala de estudos', NOW(), 'achado', 0),
(5, 30, 'Camiseta preta com estampa de banda', 'camiseta1.png', 'Pátio', NOW(), 'perdido', 0);
SELECT * FROM objetos;


INSERT INTO feedbacks (usu_id, fbck_mensagem, fbck_data_envio, fbck_avaliacao) 
VALUES 
(1, 'Ótimo atendimento, muito satisfeito!', NOW(), 5),
(2, 'A experiência foi boa, mas poderia melhorar.', NOW(), 4),
(3, 'Não gostei do serviço prestado.', NOW(), 2),
(9, 'Tudo perfeito! Recomendo muito.', NOW(), 5),
(5, 'Tive alguns problemas, mas foram resolvidos rapidamente.', NOW(), 4),
(6, 'Atendimento razoável, esperava mais.', NOW(), 3),
(7, 'Muito bom! Fiquei satisfeito com tudo.', NOW(), 5),
(8, 'Poderiam melhorar o tempo de resposta.', NOW(), 3),
(9, 'Serviço de qualidade, equipe atenciosa.', NOW(), 5),
(10, 'Não recomendo, tive vários problemas.', NOW(), 1),
(1, 'O suporte foi excelente, resolveram rápido.', NOW(), 5),
(2, 'Gostei bastante, voltarei a usar o serviço.', NOW(), 4),
(20, 'Nada satisfeito, atendimento demorado.', NOW(), 2),
(4, 'Ótima experiência, tudo conforme o esperado.', NOW(), 5),
(7, 'Bom serviço, mas pode melhorar.', NOW(), 4),
(6, 'Equipe bem treinada, atendimento nota 10.', NOW(), 5),
(7, 'Achei caro pelo que foi oferecido.', NOW(), 3),
(23, 'Me senti bem atendido, equipe simpática.', NOW(), 5),
(9, 'Demorou muito para resolverem meu problema.', NOW(), 2),
(30, 'Tudo excelente, do início ao fim.', NOW(), 5),
(1, 'Amei o atendimento, continuem assim!', NOW(), 5),
(2, 'Boa experiência, voltarei a utilizar.', NOW(), 4),
(3, 'Fiquei decepcionado com o suporte.', NOW(), 2),
(21, 'Tudo ótimo, recomendo sem dúvidas.', NOW(), 5),
(5, 'Achei o sistema um pouco confuso.', NOW(), 3),
(15, 'Rápido e eficiente, gostei muito.', NOW(), 5),
(7, 'Tive dificuldades, mas foram atenciosos.', NOW(), 4),
(8, 'Nada a reclamar, tudo excelente!', NOW(), 5),
(9, 'Suporte poderia ser mais ágil.', NOW(), 3),
(17, 'Uma das melhores experiências que já tive.', NOW(), 5);
SELECT * FROM feedbacks;

INSERT INTO reservas (obj_id, usu_id, res_data, res_status) 
VALUES 
(1, 23, NOW(), 'pendente'),
(2, 20, NOW(), 'retirado'),
(10, 17, NOW(), 'pendente'),
(4, 4, NOW(), 'pendente'),
(24, 5, NOW(), 'retirado'),
(6, 10, NOW(), 'pendente'),
(30, 9, NOW(), 'retirado'),
(7, 8, NOW(), 'pendente'),
(9, 9, NOW(), 'retirado'),
(6, 10, NOW(), 'pendente'),
(11, 26, NOW(), 'retirado'),
(12, 20, NOW(), 'pendente'),
(21, 13, NOW(), 'pendente'),
(14, 28, NOW(), 'retirado'),
(30, 15, NOW(), 'pendente'),
(16, 16, NOW(), 'retirado'),
(17, 22, NOW(), 'pendente'),
(18, 18, NOW(), 'retirado'),
(19, 1, NOW(), 'pendente'),
(2, 20, NOW(), 'pendente'),
(21, 5, NOW(), 'pendente'),
(30, 22, NOW(), 'retirado'),
(23, 1, NOW(), 'pendente'),
(24, 6, NOW(), 'retirado'),
(25, 25, NOW(), 'pendente'),
(26, 8, NOW(), 'retirado'),
(27, 27, NOW(), 'pendente'),
(10, 28, NOW(), 'retirado'),
(29, 15, NOW(), 'pendente'),
(2, 30, NOW(), 'pendente');
SELECT * FROM reservas;


DELETE FROM reservas WHERE usu_id > 0;
ALTER TABLE reservas auto_increment = 1;